move reg and wire declaration before their use to compile by current iverilog
Icarus Verilog version 10.1 version distributed
with Debian Stretch requires this change.

Without declarations multiple errors of following cause are reported

error: duplicate declaration for net or variable 'regwrite_s5' in 'cpu'.

Signed-off-by: Pavel Pisa <pisa@cmp.felk.cvut.cz>